Added Start of the python application in backend build

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -30,8 +30,22 @@ backend_build:
       - backend/.venv/
   script:
     - cd backend
-    - echo Baue das Backend
+    - echo "Building the Backend"
     - pip install --cache-dir .cache/pip -r requirements.txt
+    - echo "Starting the Python application"
+    - python main.py &
+    - APP_PID=$!
+    - sleep 10 # Allow some time for the application to start
+    - if ps -p $APP_PID > /dev/null
+      then
+        echo "Application is running"
+      else
+        echo "Application failed to start"
+        exit 1
+      fi
+    # Clean up: stop the application
+    - kill $APP_PID 
+
 
 
 react_test:
